name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DOCKER_IMAGE_TAG: ${{ github.sha }}
      run: |
        GIT_COMMIT_ID=$(git rev-parse --short=7 ${DOCKER_IMAGE_TAG})
        docker build ./app --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/books:latest --tag ${{ secrets.DOCKERHUB_USERNAME }}/books:${GIT_COMMIT_ID}
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push the Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/books:latest

